### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by florincatalin**
images are not 100% transparent in ColorBox

### CODE REVIEW

**Comment by juek** [comment]
This rule is not about images, it's about the caption bar. Or more specific...

#cboxTitle:empty + #cboxCurrent:not(:empty) {...}

means, if the Title is empty (none set), the 'Current' counter (Image X of N) will build the semi-transparent black overlay bar. If the title is not empty, the bar overlay will be created by the Title. If both are empty there shouldn't render a bar at all. It both are not empty, the 2 rgba color backgrounds would both render, hence the counter would have a darker background than the rest of the caption bar.

**Comment by juek** [comment]
> images are not 100% transparent in ColorBox

Can you drop a screenshot please. I can't see any issues with images and transparency here.

**Comment by florincatalin** [comment]
I'm sorry, you're right, the problem was here not there:
```
#cboxContent,
{#cboxLoadedContent
margin: 0;
z-index: 9999;
}
```

lacked only the` z-index: 9999;`
So there came and lack of transparency and also image zoom don't work when I use Simple_box_1 style, because the image loaded was behind the overlay.

**Comment by juek** [comment]
z-index: 9999;

should already be set by the original colorbox.css (example 1-6) but it won't hurt to set it one more.

**Comment by florincatalin** [comment]
> should already be set by the original colorbox.css (example 1-6) but it won't hurt to set it one more.

yes, it's true, but when we set another style, I think that original colorbox.css don't work anymore, so we need to set z-index again and problem is solved

**Comment by juek** [comment]
Must be something different. The selected default style (set in TS Configuration) will always be loaded by Typesetter. So we only overrule them via precedence by loading our custom styles. The default z-index (9999) will be used, if we don't overrule. If there is a different z-index (other than 9999) defined in your case, it must be set by a theme or other plugin. Browser Dev Tool should be able to reveal where it comes from.

**Pull request merged**
